### PR TITLE
Run on FH integration

### PR DESCRIPTION
**Pull request by ReDeiPirati**
Hi @bmccann , here's the Run on FloydHub integration.

- Added the button (and the badge) in the `README.md`
- Added the `floyd.yml` config file to specify the environment and the datasets to attach 
- Added the `floyd_requirements.txt` file to automatically install the extra dependencies in the environment

Looking forward to your feedback :)

### CODE REVIEW

**Comment by bmccann** [comment]
Wow, unbelievable how slow I was on the PyTorch 0.4.1 migration. Is it possible to update the Run on FH to work with the updated code base?

**Comment by bmccann** [comment]
Just checking in on this.

**Comment by ReDeiPirati** [comment]
Hi @bmccann, sorry for the delay, let me re-test the PR for the latest update and I'll get back to you in a couple of days.

**Comment by ReDeiPirati** [comment]
Sorry @bmccann for the delay, I lack the time to update the integration at the moment, I'll definitively reopen the PR when I'll find the time later.

**Pull request closed without merging**
